H = int(input('enter the total number of heads'))
F = int(input('enter the total number of feet'))
c = int( (4 * H -F) /2)
g = int(H - c)
print('the number of goats are',g)
print('the number of chicken are',c)